//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string Sename { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
